### ISSUE TITLE
URL handler na iOS nefunguje

### ISSUE THREAD

**Issue by celuchmarek** [slovensko-digital/avm-app-flutter#16]
Nainštalujem aplikáciu z AppStore do iPhone a všetko funguje ok - aj skenovanie QR kódu priamo v appke. Avšak, pri naskenovaní QR kódu cez aplikáciu fotoaparátu sa adresa otvorí v prehliadači. Tým pádom súdim, že URL handler sa nejako nechytá.

**Comment by Matej-Hlatky** [comment]
`avm:` schema funguje?

Pre https://autogram.slovensko.digital treba v projekte overit, ci je dobre sparovana domena - https://autogram.slovensko.digital/apple-app-site-association

Sources:
- https://developer.apple.com/ios/universal-links/
- https://developer.apple.com/documentation/xcode/supporting-associated-domains

**Comment by celuchmarek** [comment]
Bolo to treba dať ešte za `.well-known/`. Overil som cez `curl -v https://app-site-association.cdn-apple.com/a/v1/autogram.slovensko.digital`. Nainštalovaná appka si to updatne vraj raz za týždeň, takže fix sa neprejaví hneď, ale malo by to už byť ok.
