### ISSUE TITLE
Ak neexistuje priečinok Downloads, nedá sa uložiť súbor

### ISSUE THREAD

**Issue by celuchmarek** [slovensko-digital/avm-app-flutter#18]
Prišlo nám od userov - ak mám priečinok Downlaods nazvaný nejako inak (čiže vlastne neexistuje), na konci podpisového flowu úspešne podpíšem dokument, ale na konci sa ho nepodarí uložiť.

Vieme toto nejako riešiť? Prípadne v tom prípade dať userovi na výber nejaký dialog, aby si vybral umiestnenie?

**Comment by Matej-Hlatky** [comment]
Aka platforma pls.?
Je mozne ten folder vobec zmazat?

S tymto pripadom sa pocita:
- zobrazi sa Snackbar s error message
- a stale ma moznost Share

**Comment by celuchmarek** [comment]
Hmmm, na Andoride. Skúsil som aj ja - premenoval som Downloads na niečo iné.

A nie je pravda, že by tam bol share button 🤔 Asi je niečo zle @Matej-Hlatky

**Comment by Matej-Hlatky** [comment]
Hej. **Share** button tam nie, ale povodne tam bol.

Tak ake je riesenie?

**Comment by celuchmarek** [comment]
Podľa mňa vrátiť ten share button (neviem, prečo zmizol). A možno odchytiť tento konkrétny error pri ukladaní a niečo podľa toho spraviť.

Ja si viem predstaviť ako easy fix, že na tento posledný screen dáme primary button "Zdieľať dokument" a v prípade tohto erroru "Cannot open file" dáme tomu primary buttonu text "Uložiť dokument" - vtedy ostane na usera, že cez share nájde možnosť to niekam uložiť/poslať.

Čo myslíš @Matej-Hlatky ?

**Comment by Matej-Hlatky** [comment]
Riesenie cez ten alternativny **Share** primarny button je OK.
Nevypiseme ziaden error.
