### ISSUE TITLE
Autogram v mobile sa napichne na "i" (info k kontaktu) akciu pri kontaktoch a pokazi system

### ISSUE THREAD

**Issue by nekromoff** [slovensko-digital/avm-app-flutter#21]
"i" akcia pri kontakte ma otvarat zobraznie kontaktu a ponuknut jeh opridanie ako noveho alebo zobrazit existujuci. Namiesto toho od instalacie Autogramu v mobile sa Autogram na nu nahookoval a pokazil fungovanie Androidu. Okrem toho, ze zbytocne vypisuje chybu, ze dokument nevie otvorit, nie je mozne ho zrusit ako defaultnu akciu pre kontakty.

**Comment by nekromoff** [comment]
Ciel ej teda, aby urcite Autogram nepreberal default hook na kontakty, to nie je ziadane a je to cisty dark pattern.

**Comment by Matej-Hlatky** [comment]
ahoj,
dakujeme za report.
Popisane spravanie urcite nie je zamerom.

Pri vyvoji bola app testovana app na telefonoch zn. Samsung a Motorola a aj v emulatore a toto spravanie sa neprejavilo.

Prosim zaslat detaily:
1. O Android s akou nadstavbou ide?
2. Pre "**Contacts**", aka aplikacia je pouzivana? Je to mozne zistit sposobom: long tap na ikonu app -> **App Info** -> dole **App details** co by malo otvorit app v Google Play Store. Prosim poslat tu URL.

Dakujem

**Comment by nekromoff** [comment]
Cisty Android, Asus Zenfone 8
Aplikácia je Phone (default) verzia  3.5.1.20_230615, teda caller, k URL sa
neviem dostat, kedze taku moznost neukazuje

**Comment by nekromoff** [comment]
Takze asi Zen UI nadstavba

**Comment by Matej-Hlatky** [comment]
Dakujem za info.

Teda predpokladam, ze to je app "**ZenUI Dialer & Contacts**" (`com.asus.contacts`).
Nasiel som podobnu verziu (10.1.0.11_230727) na nete, avsak nejde to rozbehat ani v emulatore ani na Samsung device. Tym padom na teraz s tym nebudem vediet pohnut...

**Comment by Matej-Hlatky** [comment]
Bude potrebne upravit https://github.com/slovensko-digital/avm-app-flutter/blob/acd9126a2e21f6c2d71aca43e7a77b272c02fcd8/android/app/src/main/AndroidManifest.xml#L52
a namiesto `mimeType` = `*/*` vypisat Mime Type podporovanych typov suborov:
- application/pdf
- text/*
- image/*

Pre [ASiC](https://en.wikipedia.org/wiki/Associated_Signature_Containers) (".asice", ".sce", ".asics", ".scs") */* a [`pathPattern`](https://developer.android.com/guide/topics/manifest/data-element#path), avsak tusim to nefungovalo spravne.
