### ISSUE TITLE
Update Android 14

### ISSUE THREAD

**Issue by Matej-Hlatky** [slovensko-digital/avm-app-flutter#33]
Uprava Target SDK na 34 (Android 14).

[Meet Google Play's target API level requirement](https://developer.android.com/google/play/requirements/target-sdk)

**Potrebne pretestovat:**
- otvaranie suborov z dialogu
- otvaranie suborov zo share
- URL asociaciu
- nacitanie cert. a podpisovanie
- QR code scanner - Camera permission

**Dalsie upravy:**
- pub upgrade
- pripadne aj update [Flutter SDK](https://docs.flutter.dev/release/archive) na `3.19.6`?

**Comment by celuchmarek** [comment]
@Matej-Hlatky počuj, toto by sme už asi mali riešiť, že? Tam bol nejaký termín na jeseň.

**Comment by Matej-Hlatky** [comment]
> You've been granted an extension until 1 November 2024 to update your app to comply with some target API level requirements.
> From 1 November 2024, if your target API level is not within one year of the latest Android release, you won't be able to update your app.
