### ISSUE TITLE
Overovanie podpisov

### ISSUE THREAD

**Issue by celuchmarek** [slovensko-digital/avm-app-flutter#36]
na serveri už máme živý endpoint na overovanie podpisov. Vo figme máme nejaký návrh, ale ešte ho bude treba asi trochu doladiť - je pomerne ok, ale hodil by sa ešte detail jednotlivých podpis, aby si user okrem CN vedel pozrieť aj ďalšie info o certifikáte a podpise (issuer, serial number, čas podpisu, isser pečiatok, čas pečiatok, atď.). Ale teda v prvom priblížení podľa mňa spravme to, čo je vo figme s tým, že bude možné klikať na jednotlivé podpisy, ku ktorým sa otvorí detail, ktorého dizajn domyslíme. (ani tie CN a badge zatiaľ nevyzerajú najlepšie)

![Snímka obrazovky 2024-08-06 o 8 52 41](https://github.com/user-attachments/assets/733084d3-afb3-4628-8520-86cd3e8fba54)

**Comment by Matej-Hlatky** [comment]
Kebyze sekcia "**Podpisy v dokumente**" bude **jeden samostatny screen** a potom detaily podpisov uz len cez bottom sheet / modal dialog? Pretoze inak zobrazovat dialog cez dialog nie je uplne OK.

**Comment by celuchmarek** [comment]
Jop, tie podpisy v dokumente (na obrázku vpravo) pokojne môžu byť osobitný screen.
