### ISSUE TITLE
po podpise nevie správne uložiť dokument - problém s názvom podpísaného súboru

### ISSUE THREAD

**Issue by NetroSK** [slovensko-digital/avm-app-flutter#38]
po podpísaní sa zobrazí názov súboru s doplneným "signed-YYYYMMDDhhmmss" (asi) v názve a tlačítko zdieľať. Avšak názov ukladaného súboru je "Elektronicky podpisany dokument", čo sa nezhoduje s názvom prezentovaným na obazovke a navyše je bez koncovky (.pdf).

Postup na replikáciu: podpíš súbor, zdieľaj (ulož si) ho na Google Drive
Sumár issues:
1) názov súboru sa automaticky dá generický namiesto modifikovaného pôvodného s doplnením, že ide o podpísaný + časový kód
2) súbor nemá koncovku súboru (.pdf), na Google Drive sa uloží bez nej a treba ju manuálne dopísať, aby sa dal súbor otvoriť

**Comment by Matej-Hlatky** [comment]
Ahoj @NetroSK ,
dakujeme za report. Je na to spraveny PR #39 , tak ked sa to mergne, tak bude OK.

Ak je to problem, zatial pouzi Share cez Gmail, alebo inak - tam sa pouzije spravny file name.
