### ISSUE TITLE
Accessibility: Radiobuttony nemajú vytvorenú menovku

### ISSUE THREAD

**Issue by rraddatch** [slovensko-digital/avm-app-flutter#50]
Radiobuttony musí mať priradenú menovku, ktorá by popisovala, aká je funkcia, resp. účel daného radiobuttonu.

Menovku je potrebné priradiť všetkým radiobuttonom v mobilnej aplikácii.

```flutter
Semantics(
  label: 'PAdES'
  ... 
);
```
![Screenshot_20241115_173950](https://github.com/user-attachments/assets/dbdc6991-aa4c-48b4-863d-6ed547ec2db0)

**Comment by beejkaa** [comment]
To isté bude treba ešte fixnúť pri podpisovaní.

https://github.com/user-attachments/assets/f5642337-d878-4a84-a89a-e32b3b2fbaff
