### ISSUE TITLE
Accessibility: Tlačidlo pre zdieľanie nemá definovanú menovku

### ISSUE THREAD

**Issue by rraddatch** [slovensko-digital/avm-app-flutter#51]
Tlačidlo pre zdieľanie musí mať zadefinovanú prístupnú menovku, ktorá by popisovala, aká je funkcia, resp. účel daného tlačidla. V tomto prípade by mala byť menovka napríklad "Zdieľať náhľad dokumentu".
```flutter
Semantics(
  label: 'Zdieľať náhľad dokumentu'
  ... 
);
```

![Screenshot_20241115_184721](https://github.com/user-attachments/assets/e8bf00de-0a0a-427e-8e3a-b3799e86a67a)

**Comment by beejkaa** [comment]
Ešte je potrebné zlúčiť dokopy, pretože teraz číta menovku a sémantiku oddelene

https://github.com/user-attachments/assets/b2e3f3a0-855e-4e4b-9bb0-ed6d569ced9c
