### ISSUE TITLE
Accessibility: Náhľadový obrázok musí mať vytvorený popisnejší názov

### ISSUE THREAD

**Issue by rraddatch** [slovensko-digital/avm-app-flutter#52]
[Len v prípade keď sa podpisuje obrázok]

Náhľadový obrázok musí mať vytvorený popisnejší názov, aby nevidiaca osoba vedela aký je účel tejto grafiky.

Nemusí byť v názve doslova uvedené čo sa nachádza na obrázku, stačí len uviesť názov "Náhľad dokumentu", aby to bolo viac user friendly.

Názov pre grafiku sa vytvára pomocou vlastnosti semanticLabel.

Príklad:
```flutter
Control(
  semanticsLabel: 'Náhľad dokumentu'
)
```
![Screenshot_20241115_184730](https://github.com/user-attachments/assets/cf52fc15-768d-4088-8527-d8bb803ef1a7)

**Comment by beejkaa** [comment]
Menovka "Náhľad dokumentu" by mal byť súčasťou grafiky.

https://github.com/user-attachments/assets/20ef209d-edba-42cc-8d13-9ff24d4441e0
