### ISSUE TITLE
Accessibility: Tlačidlo pre návrat na prechádzajúcu obrazovku nemá vytvorenú menovku

### ISSUE THREAD

**Issue by rraddatch** [slovensko-digital/avm-app-flutter#55]
Tlačidlo pre návrat na prechádzajúcu obrazovku nemá vytvorenú menovku.

Asistenčná technológia interpretuje informáciu "Neoznačené".

![PXL_20241115_181452751](https://github.com/user-attachments/assets/c1124a05-e170-49ea-8c60-de6aced5257c)

**Comment by matejkepes** [comment]
Fix je potrebny v https://github.com/eIDmSDK
