### ISSUE TITLE
Accessibility: Nadpis "Podpis dát" nemá sémantiku nadpisu

### ISSUE THREAD

**Issue by rraddatch** [slovensko-digital/avm-app-flutter#56]
Nadpis "Podpis dát" musí byť v kóde aplikácie sémanticky správne zadefinovaný ako nadpis, aby ho asistenčná technológia vedela nevidiacemu používateľovi správne interpretovať.
![PXL_20241115_181515664](https://github.com/user-attachments/assets/ae68166f-67a6-42bc-816b-50f0d603ae79)

**Comment by matejkepes** [comment]
Fix je potrebny v https://github.com/eIDmSDK
