### ISSUE TITLE
Accessibility: Step indicator nemá vytvorené menovky

### ISSUE THREAD

**Issue by rraddatch** [slovensko-digital/avm-app-flutter#57]
Paginácia nemá vytvorené menovky.

Asistenčná technológia interpretuje informáciu "Neoznačené".

![IMG-20241115-WA0026](https://github.com/user-attachments/assets/d8517aa8-9cda-4604-bb65-4f9ce228d507)

**Comment by matejkepes** [comment]
Fix je potrebny v https://github.com/eIDmSDK
