### ISSUE TITLE
Accessibility: Tlačidlo pre zatvorenie obrazovky nemá menovku

### ISSUE THREAD

**Issue by rraddatch** [slovensko-digital/avm-app-flutter#58]
Tlačidlo pre zatvorenie obrazovky nemá menovku.

Asistenčná technológia interpretuje informáciu "Neoznačené".

![IMG-20241115-WA0028](https://github.com/user-attachments/assets/458e956f-8978-44fc-a1d4-78588335853f)

**Comment by matejkepes** [comment]
Fix je potrebny v https://github.com/eIDmSDK
