### ISSUE TITLE
Accessibility: Tlačidlo pre vymazanie znaku nemá menovku

### ISSUE THREAD

**Issue by rraddatch** [slovensko-digital/avm-app-flutter#59]
Tlačidlo pre vymazanie znaku nemá menovku.

Asistenčná technológia interpretuje informáciu "Neoznačené".

![IMG-20241115-WA0022](https://github.com/user-attachments/assets/78b2a90e-784b-41ab-aa39-f50dbb3288d1)

**Comment by matejkepes** [comment]
Fix je potrebny v https://github.com/eIDmSDK
