### ISSUE TITLE
Accessibility: Tlačidlo "OK" musí informovať, či je enabled/disabled

### ISSUE THREAD

**Issue by rraddatch** [slovensko-digital/avm-app-flutter#60]
Tlačidlo "OK" musí informovať, či je enabled/disabled, pretože kým nie sú vyplnené všetky znaky, tak tlačidlo nie je dostupné. Nevidiaci používateľ o tom musí byť informovaný.

![IMG-20241115-WA0024](https://github.com/user-attachments/assets/a8624feb-9654-4be1-8e27-631b351e8916)

**Comment by matejkepes** [comment]
Fix je potrebny v https://github.com/eIDmSDK
