### ISSUE TITLE
Accessibility: Asistenčná technológia číta obsah, ktorý sa nachádza na predchádzajúcej obrazovke

### ISSUE THREAD

**Issue by rraddatch** [slovensko-digital/avm-app-flutter#61]
Asistenčná technológia číta obsah, ktorý sa nachádza na predchádzajúcej obrazovke.
Pre nevidiacich používateľov je to veľmi zmätočné.

![image](https://github.com/user-attachments/assets/054a472c-e0d5-427d-bf67-87b015f43b07)

**Comment by matejkepes** [comment]
Fix je potrebny v https://github.com/eIDmSDK
