### ISSUE TITLE
Accessibility: VoiceOver v iOS nedokáže zamerať step indicator

### ISSUE THREAD

**Issue by rraddatch** [slovensko-digital/avm-app-flutter#63]
VoiceOver v iOS nedokáže zamerať step indicator. Nevidiaci používateľ teda nevie, že v ktorom kroku z koľkých sa nachádza.

Odporúčame doplniť do step indicatora aj čísla krokov "1", "2". Aby bol step indicator prístupný aj pre faroslepé osoby (aj v Androide aj v iOS).

![image](https://github.com/user-attachments/assets/baacd98f-abf8-4a2f-88d7-121d581a2007)

**Comment by matejkepes** [comment]
Fix je potrebny v https://github.com/eIDmSDK
