### ISSUE TITLE
Accessibility: Nadpis "Zadajte Váš BOK" nemá sémantiku nadpisu

### ISSUE THREAD

**Issue by rraddatch** [slovensko-digital/avm-app-flutter#64]
Nadpis "Zadajte Váš BOK" musí byť v kóde aplikácie sémanticky správne zadefinovaný ako nadpis, aby ho asistenčná technológia vedela nevidiacemu používateľovi správne interpretovať.

![IMG_0104](https://github.com/user-attachments/assets/5a687b3f-a8ed-4660-b5d1-97db29382d93)

**Comment by matejkepes** [comment]
Fix je potrebny v https://github.com/eIDmSDK
