### ISSUE TITLE
Accessibility: Nadpis "Zabudol som BOK" nemá sémantiku nadpisu

### ISSUE THREAD

**Issue by rraddatch** [slovensko-digital/avm-app-flutter#65]
Nadpis "Zabudol som BOK" musí byť v kóde aplikácie sémanticky správne zadefinovaný ako nadpis, aby ho asistenčná technológia vedela nevidiacemu používateľovi správne interpretovať.

![IMG_0103](https://github.com/user-attachments/assets/15560347-6273-4daf-9d8d-e4082c011d38)

**Comment by matejkepes** [comment]
Fix je potrebny v https://github.com/eIDmSDK
