### ISSUE TITLE
Accessibility: Tlačidlo "Späť" nemá dostatočný farebný kontrast

### ISSUE THREAD

**Issue by rraddatch** [slovensko-digital/avm-app-flutter#66]
Tlačidlo "Späť" nemá dostatočný farebný kontrast. Text tlačidla môže byť náročnejšie čitateľný pre zrakovo znevýhodnené osoby.

Kontrastný pomer farby textu a farby pozadia musí byť aspoň 4,5:1. Minimálny odtieň modrej farby textu, ktorý spĺňa túto požiadavku je #4A74C8, prípadne sa môže použiť tmavšia farba.
https://www.w3.org/WAI/WCAG22/Understanding/contrast-minimum.html

![image](https://github.com/user-attachments/assets/46076ab0-0f4f-43a3-9f67-fd2749bf5065)
![image](https://github.com/user-attachments/assets/77ed7e8d-3316-4ac1-8936-4c556d64841c)

**Comment by matejkepes** [comment]
Fix je potrebny v https://github.com/eIDmSDK
