### ISSUE TITLE
Keď sa do mobilnej aplikácie vloží nepodporovaný formát dokumentu, tak text chyby nie je dostatočne popisný

### ISSUE THREAD

**Issue by rraddatch** [slovensko-digital/avm-app-flutter#71]
Keď sa do mobilnej aplikácie vloží nepodporovaný formát dokumentu, tak text chyby nie je dostatočne popisný.

Používateľ by mal vedieť prečo nastala chyba, napríklad "Formát vloženého dokumentu nie je podporovaný".

![Screenshot_20241116_163458](https://github.com/user-attachments/assets/0d4fb1f3-d9fa-40eb-8a27-997359ab81c1)

**Comment by Matej-Hlatky** [comment]
duplikat #42
